### ISSUE TITLE
Font size wrong on All Chats header text

### ISSUE THREAD

**Issue by kongo09** [element-hq/element-x-android#1572]
### Steps to reproduce

1. Start EX
2. Slowly move roomlist up
3. Observe how All Chats appears in the header

#### What did you expect?
Text to fade in

#### What happened instead?
Text appears briefly in large font size, jumps to small and then fades in

https://github.com/vector-im/element-x-android/assets/640121/58a0e027-d9c8-4020-9dd1-a14780b47eb3

### Your phone model

Pixel 5

### Operating system version

Android 14

### Application version and app store

latest nightly

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
That's just what the Android component ( `MediumTopAppBar`) does by default. To improve this we'd have to create our own component from scratch.

Here's a screenshot from a GIF found in the wild where the 2 states (collapsed and expanded) can be seen at the same time:

<details>
<summary>Image</summary>
<img src='https://github.com/vector-im/element-x-android/assets/480955/e47740ad-f9a2-45b9-9404-c5d8a58d83c8' />
</details>

**Comment by kongo09** [comment]
It might not be so much about being seen at the same time, but more about the font size that starts big and then jumps to small.

**Comment by kongo09** [comment]
Not sure I can follow your reasoning. If I look in the documentation, there is not jumping around, the font size is always consistent.
https://developer.android.com/jetpack/compose/components/app-bars


https://github.com/element-hq/element-x-android/assets/640121/a5315b78-bfdc-4c64-a728-6ee8382f7a23



Can you please take another look. Something else must be going on.

The legacy app doesn't exhibit this jumping problem either and the Android settings also don't show it.


https://github.com/element-hq/element-x-android/assets/640121/f61b91db-453a-4e44-a1d7-20f36f0a841a

**Comment by kongo09** [comment]
@nadonomy or do I miss something from a design perspective?

**Comment by jmartinesp** [comment]
Actually after taking another look, I think @kongo09 is right here: there is a bug that causes the title to change its size, introduced [here](https://github.com/element-hq/element-x-android/blob/fa9dd3a98e6ff0712afc59c2e387103dec323d4c/features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomListTopBar.kt#L182).

We have to do this because the underlying Material 3 component doesn't allow us to customise the text styles used for large/small title other than modifying `MaterialTheme.typography.headlineSmall` and `MaterialTheme.typography.titleLarge`, which could affect other components, although I think (it needs some double checking) only dialog titles would be affected, so it might be something we can just do.

If we wanted to both have the right text styles for dialogs and not affect any other components we might be able to do this by providing a custom `MaterialTheme` with the material typographies changed using `LocalCompositionProvider` only for this component.

Ideally, the solution would be that Google would just allow us to override these values just for this component, but that needs a feature request, and for it to actually get done an released, so it would take quite some time even if they decided they actually want to allow it.

**Comment by nadonomy** [comment]
+1 to fixing this - this is plainly a visual bug. If it needs prioritising against other work that's one thing but this for sure shouldn't be a 'won't fix'.
