### ISSUE TITLE
Unified Push (ntfy.sh)

### ISSUE THREAD

**Issue by ghost** [element-hq/element-x-android#2000]
### Your use case

In light of recent revelations about [Google's practice of storing and sharing Android user notifications with the government](https://www.axios.com/2023/12/06/apple-google-requests-push-notification-data), it is worth focusing on the inclusion of [Unified Push](https://unifiedpush.org/) in the app.

I understand that there is already an issue (#1418) suggesting the addition of Unified Push, but the Matrix network was designed as a secure communication platform. **Message encryption loses its purpose if decrypted content is sent to the government.**

Speaking from a personal perspective, I have chosen not to rely on Google services.
Application notifications are not available for me, significantly reducing the User Experience for users with similar preferences.

### Have you considered any alternatives?

No

### Are you willing to provide a PR?

No

**Comment by ninchuka** [comment]
unless they've changed the way they do it (which would surprise me) ele android doesnt send message content over FCM and it couldnt anyway in E2EE rooms, not saying it wouldnt be nice for unified push support, but from my understanding it doesnt send message content via FCM so it doesnt matter as much

**Comment by MTRNord** [comment]
as ninchuka says: The HS cant decrypt the message since as the name suggest the messages are encrypted end to end. Only the receiving party(or parties in a group) and yourself can decrypt the message. The Homeserver doesnt know the required keys to do so. So even if it were sent via push (which it is not) then you still have just an encrypted olm/megolm blob in it without the keys. So the best they can see is metadata like frequency of it, to which phone it was sent, probably to which app it was sent, and room id and event id. 

In reality in matrix there is only the room id and event id being sent and on top is the metadata which google and apple require like the certificate which delegates that the push server can send to the app and then your app did at the start register at FCM and has a UUID which is used as the target so only you get the notification and not anyone else using the app.

**Comment by SandResidence** [comment]
> from my understanding it doesnt send message content via FCM

Well, then I apologize for my ignorance and jumping to conclusions.

However, this does not mean that the Unified Push integration wouldn't be useful 🙃 Element without notifications isn't so useful 😄

**Comment by ninchuka** [comment]
yeah it would be useful and https://github.com/SchildiChat/schildichat-android-next/blob/70104ccca1e536a942ac704e9b888ef4d4ae41eb/plugins/src/main/kotlin/extension/DependencyHandleScope.kt#L92 the dependency is in just not used currently https://github.com/element-hq/element-x-android/issues/185 is the issue tracking it

**Comment by bmarty** [comment]
> The last release (0.4.2) can do UnifiedPush, so I believe this one can be closed....

Yes, but please note that it's possible yet to switch from Firebase to UnifiedPush if both Push providers are available. We may want to open a dedicated issue about it.

**Comment by Xiretza** [comment]
> Yes, but please note that it's [not] possible yet to switch from Firebase to UnifiedPush if both Push providers are available. We may want to open a dedicated issue about it.

=> #2340
