### ISSUE TITLE
Element X is not backing up the keys unless you try to logout

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-x-android#2011]
### Steps to reproduce

1. Log in EIX, verify with existing session
2. Log out all the other sessions but EX

3. repeat x time:
 - create a room
 - send a message

4. Wait for about 1 minute
5. kill the app and then uninstall from the device

6. Log back in from web using the recovery key

#### What did you expect?

To be able to decrypt the messages

#### What happened instead?

They are all in UTD
<img width="303" alt="image" src="https://github.com/element-hq/element-x-android/assets/9841565/28cd4ebb-c2b2-4e00-a12f-015198872847">

=> EAX only upload to backup if you try to logout

If instead of uninstall the app I go to logout then it will start to upload the keys
<img width="892" alt="image" src="https://github.com/element-hq/element-x-android/assets/9841565/f64b3b28-a3af-4d4d-b7f0-a50d588009a9">

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
When you go to the logout screen, the presenter is [invoking](https://github.com/element-hq/element-x-android/blob/main/features/logout/impl/src/main/kotlin/io/element/android/features/logout/impl/LogoutPresenter.kt#L60) `waitForBackupUploadSteadyState` that may trigger the uploading of the keys. I suspect that the issue is on the SDK then, or there is some method to invoke on the app side, but it should not be the case.

**Comment by bmarty** [comment]
TODO: test with the latest SDK.

**Comment by bmarty** [comment]
OK, I think it's fine with the SDK 0.1.78 (https://github.com/element-hq/element-x-android/pull/2055).

What I have done:
- create a new account with EleWeb and setup 4S (with a passphrase)
- login using Element X Android and verify the session
- logout from Ele Web
- create a new e2e room with EXA and send a message
- login again with Ele web and verify the session using the passphrase
- observe that the message sent by EXA is visible on Web

@BillCarsonFr is this OK for you? If yes, the issue can be closed 🎉
