### ISSUE TITLE
Screen lock asked again when upload media

### ISSUE THREAD

**Issue by parisni** [element-hq/element-x-android#2054]
### Steps to reproduce

1. Activate screen lock
2. Unlock elementx
3. Upload media
4. Get asked again to unlock

#### What did you expect?

Skip second unlock step

### Operating system version

Android 10

### Application version and app store

0.3.2

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
Hello, thanks for reporting. This behavior is sort of expected since we removed the grace period for the pin code. When you pick a media to upload, or when you take a photo with the camera, you are technically out of the Element X application, that's why the application requires again the code pin when it is resumed.

We could mitigate this by adding a grace period for such use case, or by implementing an internal camera / file picker, that would require more work.

**Comment by bmarty** [comment]
Closing as "working as expected"
