### ISSUE TITLE
Animated WebP on API level < 26 are not displayed

### ISSUE THREAD

**Issue by surakin** [element-hq/element-x-android#2137]
### Steps to reproduce

This might be low priority but it's worth mentioning.

While I was playing with sticker rendering I found several ones that didn't show up on the emulator on API level 23
I tried higher API levels and found this
From API level 26 they show up, but not animated.
From API level 29 they show up correctly animated.

#### What did you expect?
Animated WebP images should show up animated
#### What happened instead?
On lower API levels they either do not show or they are not animated at all

### Your phone model

Emulator

### Application version and app store

Element X 0.4.2

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
Sadly, `coil-gif`, which also adds animated WebPs beside gifs, only supports animated WebP from API 29+ (Android 9) since it's based on a new API only available in that API: https://coil-kt.github.io/coil/getting_started/#supported-image-formats.

Maybe it's possible to add support for animated WebPs with a new image decoder based on some other library, but it's not planned for now, sorry.
