### ISSUE TITLE
Applying a spell checking suggestion yields no effect

### ISSUE THREAD

**Issue by Ezwen** [element-hq/element-x-android#2140]
### Steps to reproduce

- open a room
- click on the text input field
- type a sentence with a word not correctly written, that gets underlined in red by the spell checker
- click on the underlined word, pick one of the choices offered
- send the message

#### What did you expect?

The sent message in the history should include the fix made using the spell checker 

#### What happened instead?

The message in the history does not include the fix, as if the spell checker was never used

### Your phone model

Xiaomi Mi Mix 2

### Operating system version

Lineage 20-20231204-microG-chiron

### Application version and app store

Element X 0.4.0

### Homeserver

Personal private home server 

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by spongythecake** [comment]
Can also confirm this happening to me on CalyxOS using Android AOS keyboard, but the spell checker works on a different phone Samsung keyboard.

**Comment by jmartinesp** [comment]
When you say you select one of the options, you mean from this list and not the suggestions from the keyboard, right?

![image](https://github.com/element-hq/element-x-android/assets/480955/50a45d6e-a5c8-43fc-89a2-410a0c8c042f)

Given the current implementation of the editor, it'll be extremely difficult to fix this issue, since the spellchecker completely avoids the keyboard input mechanism and just changes the text in the UI, with no way for us to notice this change and apply it in the actual state of the editor.

**Comment by Ezwen** [comment]
> When you say you select one of the options, you mean from this list and not the suggestions from the keyboard, right?

Yes!

> Given the current implementation of the editor, it'll be extremely difficult to fix this issue, since the spellchecker completely avoids the keyboard input mechanism and just changes the text in the UI, with no way for us to notice this change and apply it in the actual state of the editor.

I see, tricky indeed… How do other apps (eg. legacy Element) make it work?

**Comment by jmartinesp** [comment]
Most of the time, the EA app just uses the default Android editor, which relies only on the plain text on it instead of on external state as our rich text editor does. Maybe in the next Jetpack Compose versions they will give us a better text field component to work with and we can fix this, but at the moment it's quite unlikely that we'll find a proper fix or workaround for this...

**Comment by Ezwen** [comment]
> Maybe in the next Jetpack Compose versions they will give us a better text field component to work with

I se, then would it be relevant to open a proper issue on the Jetpack Compose side?

**Comment by Ezwen** [comment]
Seems solved on 0.4.8
