### ISSUE TITLE
Green 'new unread' icon displayed in timeline for account with 'only mentions and keywords' enabled

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#2282]
### Steps to reproduce

1. Set the notification preferences for the account to 'Only mentions and keywords'.
2. On a room using the default notification settings, receive a new message with no mentions or keywords included.

#### What did you expect?

A grey dot should appear in the room list item.

#### What happened instead?

A green dot is displayed instead.

Apparently there are 3 values for notifications now:

- RoomInfo.numUnreadMessages
- RoomInfo.numUnreadMentions
- RoomInfo.numUnreadNotifications

We should probably include all 3 of them and use them following what iOS does at the moment, since it seems like that's the right behaviour. They provided this snippet in case it helps: https://github.com/element-hq/element-x-ios/blob/33bb5c2b48b7677cb19332c0757cb4fc52a3ae02/ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift#L136-L157

### Your phone model

Xiaomi Mi 9

### Operating system version

Android 14

### Application version and app store

0.4.2 (40004020), latest develop

### Homeserver

element.io

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by bmarty** [comment]
I think that the issue is that the room list does not take into account the global notification setting. And when the `userDefinedNotificationMode` for a room is not set (so `== null`), it's considered as `RoomNotificationMode.ALL_MESSAGES`, see in the code: https://github.com/element-hq/element-x-android/blob/develop/features/roomlist/impl/src/main/kotlin/io/element/android/features/roomlist/impl/components/RoomSummaryRow.kt#L209

Will check with the iOS what they are doing here.
