### ISSUE TITLE
The app does not advertise it supports the recovery and backup passphrase

### ISSUE THREAD

**Issue by davidegirardi** [element-hq/element-x-android#2478]
#### What would you like to do?
Verify a new session or enable the chat backup by typing in the passphrase that is much easier to type than 48 random characters. The app asks for the 48-characters key but it **already supports the passphrase**. If you type it, it will work both for cross-signing and to setup the secure backup.

I think it's worth making it obvious.

#### How would you like to achieve it?
By updating the "enter your recovery key" screen.

I think by showing users that we are "Setting up the chat encryption" and/or "Setting up the secure backup", and tell them to "Enter your passphrase or the equivalent 48 character code". This proposal probably needs some coordination with regards to the first time user experience (FTUE) so users know that the passphrase and key are equivalent.

### Have you considered any alternatives?

Do not ask for the recovery key at all, only the passphrase.

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
This is @pmaier1 decision (IIRC, sorry if I'm wrong) to give priority on recovery key, in order to simplify the crypto. Actually I believe that we consider that even if passphrase are easy to remember, user may forget it. Recovery key has to be stored somewhere, since it's not possible for common mortals to memorize it. I already rise the concern internally FWIW, i.e. people who made the effort to remember the passphrase may feel stuck on this screen.

**Comment by davidegirardi** [comment]
I think remembering the passphrase is unlikely in most cases. The passphrase is just simpler to type.

**Comment by pmaier1** [comment]
See https://github.com/element-hq/element-x-ios/issues/2217.

**Comment by pmaier1** [comment]
This is done on EIX/EAX, thanks!
