### ISSUE TITLE
Add captions to sent image and video files

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#2573]
#### What would you like to do?

I want to have some UI that allows me to add captions to image or video files I'm about to send.

Now that https://github.com/element-hq/element-x-android/issues/2521 is implemented it is possible to send both a plain text and formatted caption. It would be nice to be able to send at least the plain text version, if not both.

#### Why would you like to do it?

It's weird we can display captions but not send them. It's also present in most other IM apps.

#### How would you like to achieve it?

By implementing some new design that adds a text field to the attachment preview screen displayed before a media attachment is sent.

### Have you considered any alternatives?

We could just leave it as is.

### Additional context

Something similar to WhatsApp's implementation would probably be a nice fit to expand our current UI:

![image](https://github.com/element-hq/element-x-android/assets/480955/edef44db-c62f-42f4-8574-c17a8bc0e770)

### Are you willing to provide a PR?

Yes

**Comment by surakin** [comment]
Hey! I've been playing with this, would you like to see what I've got? (I put the attachment preview above the composer instead of adding a new text field to the current preview view)

It currently looks like this
![image](https://github.com/element-hq/element-x-android/assets/683652/214f8ba7-1e9f-498f-8789-d4f36a88d93c)
