### ISSUE TITLE
Use a sane date format for day markers

### ISSUE THREAD

**Issue by piegamesde** [element-hq/element-x-android#2916]
### Your use case

I would like to never have to see a MM/DD/YYYY format while using any application. Instead, the international YYYY-MM-DD format should be used.

### Have you considered any alternatives?

An expanded format with written out day and month names, as done by Element Web for example and requested in #2637. However, implementing that would need comparatively more effort.

### Are you willing to provide a PR?

No

**Comment by Atemu** [comment]
Another possibility is to take the format from the system locale.

Unfortunately Android really sucks in this regard though as it only has a single locale setting rather than `LC_*`. There is some limited possibility to customise here as you could, for instance, use en_CA.

While I'm personally a big fan of ISO8601 dates, I could also see using the system locale being a better default.
