### ISSUE TITLE
Feature flags cannot be toggled on release builds

### ISSUE THREAD

**Issue by tonkku107** [element-hq/element-x-android#3073]
### Steps to reproduce

1. Use a release build of the app
2. Tap on the version string at the bottom of settings 7 times
3. Go to the developer settings menu that appears
4. Try to enable or disable any of the feature flags

#### What did you expect?
I expected the feature flags to change state

#### What happened instead?
Nothing happened

https://github.com/element-hq/element-x-android/assets/4409524/9d70d504-fae4-4c1b-a82d-c2dc6641c5e3

#### Additional information
@frebib in the element x android matrix room found out the cause is the static feature flag provider used in release builds
https://github.com/element-hq/element-x-android/blob/3d27f26d3c399f28e1eedd5362cff537b09b7dee/libraries/featureflag/impl/src/main/kotlin/io/element/android/libraries/featureflag/impl/di/FeatureFlagModule.kt#L41-L44

I believe the intention of #3020 was to let users toggle feature flags, since the room directory flag was specifically hidden from release builds

### Your phone model

Google Pixel 8

### Operating system version

Android 15 (Beta 3)

### Application version and app store

0.4.15 (Play store)

### Homeserver

N/A

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by jmartinesp** [comment]
True, the intention was to give full access to developer settings, but it seems like I forgot to add the dynamic provider for release builds. However, enabling this would require more effort since we'd need to rework how the default values (which FFs are enabled in debug/nightly/release by default) because right now the static provider was used as an override of the dynamic preference based one.
