### ISSUE TITLE
Reset identity iteration

### ISSUE THREAD

**Issue by bmarty** [element-hq/element-x-android#3329]
Several tasks to handle:

- [x] Ensure that wording "reset your encryption" is changed to "reset your identity"

Now that the application support resetting the identity:
- [x] Remove the button `Lost your recovery key?` in this screen:
<img width="246" alt="image" src="https://github.com/user-attachments/assets/e45f8ec1-233a-4e25-9050-d2c0bd143b37">

- [x] Remove this screen (which was displayed by the button `Lost your recovery key?`
<img width="227" alt="image" src="https://github.com/user-attachments/assets/65e6f221-63d8-49ea-a36f-a4c8bbe96c0b">

- [x] change the wording "Confirm that it's you" to "Confirm your identity"

<img width="627" alt="image" src="https://github.com/user-attachments/assets/3edbb05e-ed40-4de2-b6ad-951a77f42ffa">

- [x] Add back the banner to tell user to set up their recovery. Done in #3360

<img width="350" alt="image" src="https://github.com/user-attachments/assets/d14b6396-23e8-4b10-b00d-1aa7ba6eb14f">

- [x] Add the sign out option to unblock the user who cannot verify and does not want to reset their identity (waiting for final design) Done in #3359

### Reset legacy:
- [x] Move the confirmation dialog, which was displayed here: **EDIT: We do not change this**
<img width="198" alt="image" src="https://github.com/user-attachments/assets/58abf103-daab-4789-939b-2281fddbf73a">

on the enter password dialog:

<img width="171" alt="image" src="https://github.com/user-attachments/assets/28a3d134-3688-4ea0-bae1-2a26408d1495">

[Figma](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14436) 

### Reset OIDC

- [x] Add a confirmation screen: **EDIT: We do not add this screen**

<img width="219" alt="image" src="https://github.com/user-attachments/assets/181cd8e6-07f9-45c3-95c5-d13bf3af3415">

[Figma](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14049)

CC @pmaier1

**Comment by bmarty** [comment]
I think all the items here have been handled or cancelled, we can close the issue.

**Comment by mpeter50** [comment]
@bmarty Sorry to intervene, but resetting the indentity in this context sounds unusual.

If I understand correctly, this is a new name for the same function as it was previously, resetting the encryption, right?
To me, identity means how others know me: how others identify me and basically "my past", on the chat platform.
So in my understanding resetting the identity would present me as a different person to my chat participants, as if I was registering a new account, or similarly to how the Tor Browser uses it. However, this seems to be doing the opposite: as I see, what it resets is my "memories" on the platform.

Please consider this opinion. I'm letting you know because I think this may cause confusion for the users.

**Comment by bmarty** [comment]
@mpeter50 thanks for the feedback. You can get more details about the terminology at this page: https://github.com/matrix-org/matrix-spec-proposals/blob/andybalaam/crypto-terminology/proposals/4161-crypto-terminology.md
