### ISSUE TITLE
[Shields] Shields disappearing when a session is removed

### ISSUE THREAD

**Issue by jmartinesp** [element-hq/element-x-android#3411]
### Steps to reproduce

1. Log into a new session, don't verify it.
2. Send a message, it appears with the red shield.
3. Verify it.
4. Send a message, it appears with no shield.
5. Log out of the session.
6. In the other side, both messages don't have a shield.

#### What did you expect?

According to @BillCarsonFr , both messages should have red shields since the session is no longer valid at the time of decryption.

#### What happened instead?

Sometimes they flicker in the timeline between 1 having a red shield and the other not having one, and none of them having the shields. Most of the time they don't have shields at all.

### Application version and app store

EX 0.5.3-nightly (40005030)

### Homeserver

element.io

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by BillCarsonFr** [comment]
Since the 5th August - we create and store SenderData when the session is created ( [#3543](https://github.com/matrix-org/matrix-rust-sdk/issues/3543)), and we calculate the VerificationState using it ([#3782](https://github.com/matrix-org/matrix-rust-sdk/pull/3782))

And since this change https://github.com/matrix-org/matrix-rust-sdk/issues/3751 the sender data (authenticity of the key) is updated.

So the observed behavior is now expected, and is a very good improvement compared to how it used to be!
