### ISSUE TITLE
Click on notification to open chat, type on keyboard not working

### ISSUE THREAD

**Issue by 0verEngineer** [element-hq/element-x-android#3572]
### Steps to reproduce

1. Click on a notification to open the chat
2. The Keyboard is visible
3. Typing on the Keyboard does not work because the cursor is not set in the message field

#### What did you expect?
If i do this i expect the cursor to be in the message field

#### What happened instead?
See above

### Your phone model

Google Pixel 7 Pro

### Operating system version

Android 14

### Application version and app store

0.6.4 from Github releases

### Homeserver

Synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by Devenda** [comment]
I too have this issue.
Additionally, but probably unrelated, the text box needs a rather precise touch to actually select it and start typing.

**Comment by voc0der** [comment]
Subbed, also having this issue.

**Comment by voc0der** [comment]
Hello, this is not fixed in the latest version. It seems like it should've been based on the release notes.

If someone sends me a message, I cannot reply in the notification, and further, if I click the notification, it does not automatically prompt the keyboard open. I can't tell what changed? 

Samsung S24 here. Both users on new ver.

**Comment by voc0der** [comment]
@ganfra Hello, this is not fixed in the latest version. It seems like it should've been based on the release notes.

If someone sends me a message, I cannot reply in the notification, and further, if I click the notification, it does not automatically prompt the keyboard open.

I have to click the text input box to bring up a keyboard. The problem is the 2 extra steps. The notification thing I dont know if you'll fix because of e2e, but otherwise...

I can't tell what changed?

Samsung S24 here. Both users on new ver.

I don't think we need a new ticket, this is the right description still.
